### ISSUE TITLE
Python 3.8 is no longer supported

### ISSUE THREAD

**Issue by aheifetz** [TractorZoom/sam-cli-action#10]
It looks like the Docker container was downgraded to python 2.7  which gives this error when using python 3.8:

Build Failed
Error: PythonPipBuilder:Validation - Binary validation failed for python, searched for python in following locations  : ['/usr/local/bin/python'] which did not satisfy constraints for runtime: python3.8. Do you have python for runtime: python3.8 on your PATH?

**Comment by cody-hoffman** [comment]
https://github.com/TractorZoom/sam-cli-action/blob/e482ab12eefd4ac0864c85a39a8a2337a9ba7c4b/Dockerfile#L1 it looks like it's using Python 3.7 not 2.7

**Comment by twebber90** [comment]
@aheifetz change for this has been merged 👍
