### ISSUE TITLE
Template.yml not found

### ISSUE THREAD

**Issue by fernandosolivas** [TractorZoom/sam-cli-action#12]
**Describe the bug**
The action can not found the template.yml in root of repository.

**To Reproduce**
1. Create a new repository with nodejs
2. Add the action to .yml file in root directory
3. Commit and push

**Expected behavior**
It should recognize the file in the root directory or at least the message should point to the correct expected directory.

**Screenshots**
<img width="1304" alt="Captura de Tela 2020-07-17 às 09 59 10" src="https://user-images.githubusercontent.com/61621180/87788960-a4eb3300-c814-11ea-9355-4d55673a86e3.png">

<img width="285" alt="Captura de Tela 2020-07-17 às 09 59 48" src="https://user-images.githubusercontent.com/61621180/87789042-bdf3e400-c814-11ea-9a2d-c6d90325690e.png">

**Comment by cody-hoffman** [comment]
This looks like an issue with your setup. We have multiple projects deploying daily with this action using a `template.yml` in the root. Are you able to deploy this project via the sam cli locally?

**Comment by fernandosolivas** [comment]
Originally I thought that was a setup problem but locally I am able to build and deploy normally as you can see at this screenshot below.

*the timezone is GMT-3

<img width="1584" alt="Captura de Tela 2020-07-17 às 10 50 54" src="https://user-images.githubusercontent.com/61621180/87793281-6b69f600-c81b-11ea-86e4-d82e7f0e8d24.png">

**Comment by cody-hoffman** [comment]
Do you have a samconfig file that needs pushed up to your github repo?

**Comment by fernandosolivas** [comment]
Yes, I have.
```
version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "scale-api"
s3_bucket = <name>
s3_prefix = "scale-api"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
```

**Comment by fernandosolivas** [comment]
Here are the job action and repo: https://github.com/fernandosolivas/scale-api/runs/882256802

This action is an amazing job, so I am trying to debug the source code in entrypoint.sh and add more "debuggable" info to contribute to fixing or at least put more information.

**Comment by cody-hoffman** [comment]
You could try `sam build -t template.yml` to make sure it can find your template

**Comment by fernandosolivas** [comment]
I've found the error. As you pointed before was an action setup problem. Thanks for your attention and really great job in this action!

**Comment by matheushent** [comment]
I am facing the following error:

```bash
Error: PythonPipBuilder:ResolveDependencies - Requirements file not found: /tmp/samcli/source/requirements.txt
```

Any guess on what is going on?

**Comment by kmehtaJRNI** [comment]
@fernandosolivas What was the issue in the action? I am facing the same problem but not able to locate the issue. :(
