### ISSUE TITLE
There no deploy confirmation

### ISSUE THREAD

**Issue by GABAnich** [TractorZoom/sam-cli-action#16]
**Describe the bug**
I want to deploy my changes, and I should confirm it by pressing "y".
AWS SAM is waiting on input, but the input doesn't come, and changes aren't deployed.
```
Previewing CloudFormation changeset before deployment
======================================================
Deploy this changeset? [y/N]: 
Aborted!
```

**Expected behavior**
Should be input `y` and changes should be deployed

**Comment by cody-hoffman** [comment]
@GABAnich you need to set this up in your `samconfig.toml`. `confirm_changeset = false`

https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-config.html
