### ISSUE TITLE
Error: No changes to deploy. Stack samcount is up to date

### ISSUE THREAD

**Issue by kaihendry** [TractorZoom/sam-cli-action#22]
https://github.com/kaihendry/count/runs/1598477559#step:5:12 fails when there are no changes.

Why isn't `--no-fail-on-empty-changeset` the default or at least an option?

Thank you!

**Comment by cody-hoffman** [comment]
We add it as an option to our `sam_command` like so:

```yaml
with:
    sam_command: deploy --no-fail-on-empty-changeset
```

**Comment by twebber90** [comment]
@cody-hoffman can this be closed?
